### ISSUE TITLE
Make sure analytics are unobtrusive

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mtdo#347]
Firefox warns that the site is tracking users. It's possible that removing the Facebook SDK solves this. If not, check Google analytics. We value the privacy of our users.

**Comment by nedtwigg** [comment]
The Firefox warning seems to be gone, but we should still double-check our analytics configuration.  meta.mytake.org has google-analytics integration, but it's empty right now.

**Comment by nedtwigg** [comment]
On `meta.mytake.org`, we have configured our domain tracking like so:
<img width="636" alt="Screen Shot 2020-09-29 at 9 19 30 AM" src="https://user-images.githubusercontent.com/2924992/94585790-56efa400-0235-11eb-922a-6507ebacbd17.png">

On `mytake.org`, we are using the Cloudflare app to inject the analytics script, configured like so:
<img width="473" alt="Screen Shot 2020-09-29 at 9 09 52 AM" src="https://user-images.githubusercontent.com/2924992/94586049-a03ff380-0235-11eb-8697-ed24c2e8d338.png">

Within the google analytics dashboard, we have configured everything to to the full-privacy setting:

<img width="418" alt="Screen Shot 2020-09-29 at 9 10 12 AM" src="https://user-images.githubusercontent.com/2924992/94586157-c1084900-0235-11eb-903d-6b986ad3284f.png">

<img width="279" alt="Screen Shot 2020-09-29 at 9 10 24 AM" src="https://user-images.githubusercontent.com/2924992/94586167-c4033980-0235-11eb-9b24-ee4f9a03cfaa.png">
